apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: openebs-cstor
chartName: cstor
chartRepoUrl: https://openebs.github.io/cstor-operators
chartVersion: '2.8.0'
releaseName: openebs-cstor
releaseNamespace: openebs
extraArgs:
  - --include-crds
  # - --set rbac.create=true
  # - --set rbac.pspEnabled=false
  # - --set serviceAccount.create=true
values: ./configs/cstor-helm-chart-values.yaml
