apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - ../../base
  - ./resources/oauth-middleware.yaml
  - ./resources/ingress.yaml
  - ./resources/services.yaml
  - ./resources/404-page.yaml

generators:
- |
  apiVersion: viaduct.ai/v1
  kind: ksops-exec
  metadata:
    name: not-important
  files:
  - ./secrets/oauth2-proxy-secrets.yaml

images:
- name: ghcr.io/berbiche/cringy-404-page
  newTag: master@sha256:f936a258e3f961eeb89461980f175898e6e460456416492e37ab01df44def166
