apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: democratic-csi

resources:
  - ./resources/namespace.yaml

helmGlobals:
  chartHome: ./charts

helmCharts:
- name: democratic-csi
  releaseName: democratic-csi-iscsi
  version: 0.13.5
  repo: https://democratic-csi.github.io/charts/
  namespace: democratic-csi
  includeCRDs: true
  valuesFile: ./resources/helm-chart-values.yaml
