apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager
  namespace: operators
spec:
  channel: stable
  installPlanApproval: Manual
  name: cert-manager
  source: operatorhubio-catalog
  sourceNamespace: olm
  startingCSV: cert-manager.v1.6.1
