apiVersion: v1
kind: Secret
type: Opaque
metadata:
    # Keep in sync with the k
    name: truenas-iscsi-driver-config
    namespace: democratic-csi
    labels:
        app.kubernetes.io/name: democratic-csi
        app.kubernetes.io/instance: democratic-csi-iscsi
        app.kubernetes.io/managed-by: democratic-csi
    annotations:
        kustomize.config.k8s.io/behavior: create
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:Udw/gMpqaJc4ddNei9JHAJz0Ie66YiUI8lbuL3HFaLk3lldT8GW8s4z1gkPWBTJaF0EA8v7YGhlWgGbeDOtviqlSBLX22RYwKjKxnYNnDWjAniXg+aN3MdeLB+Ny4t1r/SX1cGh7lw9BSGYQ0PiYcDwdXj2HLJhQHtjlRVH2MXZ3EeMQrfYFUfyYPHmQlLYKU/Qpdek7wHiZEdI740LA944eBrcpK01UZg1ZnA6dbZnrI1eblGXezQacNbbeYDkFEp0w5WiGWowWemwYmDktYecjg8P56+cAhMZmVWFeqJowCk7tpcvl5Suh/zUC8wYHbdWXw2fUCcEekYmIsKYoMO45qK2/TnOVvyCar5xw8HvMJDBNWgjNj7IQmkKgOZebQLTweHR5qW+p1U8JE9FlZwMhJs5Gtsy84X7qUbg1QMatr9xtoXahDB9zcvcJLqGmUETe51HAlz8k3eNLh/PuifOBrP8WNgIYFXNhey2NknU58iihutyQqZlYM1eEP7WVL1y6+PlfJsC4y41grNrfQeGhMVQmDlxO+q+ebr5L0DfyUtpDAX3u/7aDWM2cam6SO8II0/p0rK9ndKibGpY+P4CPDAmg45V0UjCSzJBLn4xaxXTNEHnGFKvIaPuLVB9ncalmbQ1tofGZ0o2NoujSOApF3RAR0m79nX5wHeBr4HSimvN8qguexajwOb+XwoXPtjWSSDYGbsS0w8CtFK9y9hgD5lyjvpVRTRgWp1JeZuINHxTmSN3gtyS+rI/mlAqFLPYGmtDxZPDLECqB9h4gFml49K22Iod841bE3XvNTZrzO9pmEE9Xib8hAHAeEU4imKRGAK4Pl+NEKwXI0tqt9XilwzTHAqmQF0uIgBU7VC4tpVWz5AcMPQl0mHDc/qtcvNrxaVeNFLB2HztzPYtAJBwx1IT88mn0XZHOlTvq9fJ31Z2pF49poCP2CX8aWNOccsJvd/2k8Ofj5alBuRNiL8hO4j8nRXvW7WKt1x8/q+Ho7eC+AKneDU0QVE0C2hj630NyOi8NdsW0jAXbRSPXL5pe2GDGYxFkIe0tp69Vgdfoo9RBFypM90SIunwNNo0Y1u7ju2tgy4ofHClbkccK0eHgXrykAA9Eo6O7VQrgVpjGu3JCjrOeZp1dAzd/xY8F0L9h9Q8bTwRnWn5wol0ywEs1dwtVs+ctUQQZfBqTJYoakqtSAvnbOCrU6R55ObChKylUS/921fnzaetSJGRVzpGjaGBswymgDYwMTNf84eQnOCZfSuhSi7pf+tzVFZNh/cLSvTGLXNnfmvYdHGs4riJ7CvaTPFMjJSmMMBTxtgqebUg1pGvJjuqfMTO0pw0hssLoSATe2/QfKu7GTBi1aX+CjTByD6ah7MIT/zvFl0Nhv6pgyGwNrdlal7DZBTlJMcGXuxI2EI53BINQVEtKI+7oTaUOztR+DKXVawfWsh2ioYfdR4IkyBB/N5HSgKJtJGNeua/TBR1W18OsH+pQHMGZIj3IlCMeh5rP95MLoEZmc9H5xM+WgKsLcDe5I3l4z+eZ+ThfKNhYnGINQ2YEUTI0KMw4XSPOzhuA3ZfHTi4qF+Xifl1lumPAd9kpCDNrQDqRjBAXwN2oMEPbbl7bN94mA0mpDMAyhJaFN6EWSDFa0xjfZEVuts8ui7+xu1yvJsNAl8c6TEqyYHkXlmuOhkNZbhvur+dohgZQLehvNRmBWohn7AUkMYRonQbHM9FdH5GAAEjKLa776Ml89YTjXtULg9ZlQ/9izLUrrwbe3wXeQ3TfjEGNv+n6x2AfkKg+dziebc9trn8Re5ytEj//tokJuqZNJG5I1NtITiLnJyi+kZ1N39fqhnjxaVeFBJoup0bNhtVUdKjsndUv1g0I+jMUK5rj,iv:AfksxIK39/OKGquQKqb7uGuqQ5T/Qcc2RIB1aYLsQTs=,tag:FuMbrIIbauDnGaCfwSI9jA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-05T03:59:30Z"
    mac: ENC[AES256_GCM,data:y/MefgdaaY3tHb1qPL0UaH1Pzl+Z8gXL1QJUMJgt3vrl7O7HxMoJv7uL/1OvYU7SoulY2TZ7tni85Q78/f80Hld5ch+3CZF7pXZKUAkCTOhtL+otbDWoOGh67XN+umLEyBJQQHCD3U4iGTNt2LojAf6VOFwRbr02nRcI28SOyHE=,iv:ofW/RJsIx9aZ43OwGEbeQx8XtUd8sZ1FboxUhDwiM7M=,tag:B4AGoZntHsI8JQReZLSzCw==,type:str]
    pgp:
        - created_at: "2023-01-05T03:25:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA2hwEhv/EBDcAQ//ezIlUdrApEFoJ1weyPDFXEIYve9l0tiUGPSe2CX9MJs2
            aEql8APnqDDxdNy7l6gQ6JRewAba7/1YF6aPAw9Da6WMlBiYLOkFKWc1kDflnK0k
            y0/2pcs2DTDBIWtCR3kABr4RQXfjyTULN23RDKthBxzfanYA2bI7zlmQR3YgXjOn
            frvbrabi85mNqI+Igpj9TEJGMJ2pQbH/3wT7dxn9/IPhdbiILd7f9jhgw3OQQB3U
            JKkZ0XFel6yg6nPf7RHkRcHh187aeHMpDHDVw70E3WcPk5ntROv452Q/hRKcKigZ
            F+I8tHaUcsooF9FVdAtI9npdVqbHt9kvQdAP0UousT0R0aW7CQJGXy5MNb2tg8RD
            dN5fFUy1JaPzOD84QRNHBcZJCOKLUEx112uyFUqTn54NyNKr+x8ryp9hZX+wkskA
            VkhvYT2o8aSSYW7nSY8K7LOZOq7qLiSzxzOppkS+PueBvEAo8ln37Ko0+BQ57HA9
            Um/RAXoScjKbbufat5eSeFlcNUyae3wSN3Ov8LLOzA4OqbsKnhL1lmAwxR6cSzLQ
            R6Fn95Mj7qkDqw1X0WwweSvNofGnk4R7M3ricKm+Rsy1pp7A/i5xo66lFNyStovV
            +By4+V0lVR43j1AyVEn7xiSH8YxaeUsZ+8WdenazHlrh0iR4PvvjM3UId70eDEjS
            UQG0OwWO0ahjflcJqDXtbwaAC3NWJuRzh/Z7hMyyYlu0XzZe3cfyqRvFJnSTpsO3
            B1GsH3q/ZLfJMRTAWKI/kLQwuXL+DLAGPOnPwuptZ+Rc6w==
            =/nXj
            -----END PGP MESSAGE-----
          fp: 328820E009708FDD29C08DBA1D0261F6BCA46C6E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
