apiVersion: openebs.io/v1alpha1
kind: MayastorPoolList
items:
  - apiVersion: openebs.io/v1alpha1
    kind: MayastorPool
    metadata:
      name: node1-mayastor-pool
    spec:
      node: node2
      disks: ["/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"]
  - apiVersion: openebs.io/v1alpha1
    kind: MayastorPool
    metadata:
      name: node2-mayastor-pool
    spec:
      node: node3
      disks: ["/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"]
  - apiVersion: openebs.io/v1alpha1
    kind: MayastorPool
    metadata:
      name: node4-mayastor-pool
    spec:
      node: node4
      disks: ["/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"]
# spec:
#   nodeSelector:
#     openebs.io/engine: mayastor
#   # Only one disk is supported per pool as of v0.8.0
#   disks: ["/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive_scsi1"]
