keys:
  - &mine 328820E009708FDD29C08DBA1D0261F6BCA46C6E
creation_rules:
  - path_regex: k8s/.*$
    encrypted_regex: '^(data|stringData)$'
    key_groups:
    - pgp:
      - *mine
  - path_regex: bootstrap/.*\.yaml$
    key_groups:
    - pgp:
      - *mine
  - path_regex: secrets/.*\.(txt|ya?ml)$
    key_groups:
    - pgp:
      - *mine
      - 31DC3B2FBD6F216874FB823BBA4DE64771F67D4E
      - BD8A6B2B1C125E4B821E2BA5C03C8BEEBE3644EE
  - path_regex: nixos/secrets/.*$
    key_groups:
    - pgp:
      - *mine
      - 5E02F6C4D9122B94463AF801E1190F4A0FD941D9
      - 1BFC23B6C2EB75C0AC155B523E4ECA0E3BDEE7AD
      - 31DC3B2FBD6F216874FB823BBA4DE64771F67D4E
      - BD8A6B2B1C125E4B821E2BA5C03C8BEEBE3644EE
