csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.iscsi"
  fsGroupPolicy: ReadWriteOnceWithFSType
  storageCapacity: true

# add note here about volume expansion requirements
storageClasses:
- name: truenas-iscsi-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    fsType: ext4
  mountOptions: []
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
      node-db.node.session.auth.authmethod: CHAP
      # These values are changed by replacing the secret with Kustomize
      node-db.node.session.auth.username: change-me
      node-db.node.session.auth.password: change-me
    node-publish-secret:
    controller-expand-secret:

controller:
  driver:
    imagePullPolicy: IfNotPresent
  externalProvisioner:
    extraArgs:
    - --volume-name-uuid-length=16

# Openshift specific settings
node:
  driver:
    localtimeHostPath: false
  rbac:
    openshift:
      privileged: true

# Driver configuration
driver:
  existingConfigSecret: truenas-iscsi-driver-config
  config:
    driver: freenas-api-iscsi
    instance_id: ""
    httpConnection:
      protocol: https
      host: truenas.node.tq.rs
      port: 443
      allowInsecure: false
      # Replaced by value in encrypted config
      username: CHANGE-ME
      # Replaced by value in encrypted config
      apiKey: CHANGE-ME
      apiVersion: 2
    zfs:
      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
      datasetParentName: tank/kubernetes/iscsi/vols
      detachedSnapshotsDatasetParentName: tank/kubernetes/iscsi/snaps
      zvolCompression: "" # inherit
      zvolDedup: "" # inherit
      zvolEnableReservation: true
      zvolBlocksize: "16K"
    iscsi:
      targetPortal: "truenas.node.tq.rs:3260"
      # leave empty to omit usage of -I with iscsiadm
      interface: ""
      # Don't enable this, the generated names are too long and causing failures
      #nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      namePrefix: csi-
      nameSuffix: "-cluster"
      # Replaced by value in encrypted config
      targetGroups:
      - targetGroupPortalGroup: 1
        targetGroupInitiatorGroup: 1
        targetGroupAuthType: CHAP
        targetGroupAuthGroup: 1
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 4096
      # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
      extentRpm: "SSD"
      # 0-100 (0 == ignore)
      extentAvailThreshold: 0
