# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: argocd-argocd-applicationset-controller
#   namespace: argocd
# spec:
#   ingress:
#   - from:
#     - namespaceSelector: {}
#     ports:
#     - port: metrics
#   podSelector:
#     matchLabels:
#       app.kubernetes.io/instance: argocd
#       app.kubernetes.io/name: argocd-applicationset-controller
#   policyTypes:
#   - Ingress
---
- op: add
  path: /spec/ingress/-
  value:
    from:
    - namespaceSelector: {}
    ports:
    - port: webhook
      protocol: TCP
