apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cstor-raidz-disk-pool
  namespace: openebs
spec:
  resources:
    requests:
      memory: "2Gi"
      cpu: "250m"
    limits:
      memory: "4Gi"
      cpu: "500m"
  auxResources:
    requests:
      memory: "500Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "200m"
  pools:
    - nodeSelector:
        kubernetes.io/hostname: node2
      poolConfig:
        dataRaidGroupType: stripe
        compression: lz4
      dataRaidGroups:
        - blockDevices:
          - blockDeviceName: blockdevice-8a87314da7282e6d55c08a58ae96e656
    - nodeSelector:
        kubernetes.io/hostname: node3
      poolConfig:
        dataRaidGroupType: stripe
        compression: lz4
      dataRaidGroups:
        - blockDevices:
          - blockDeviceName: blockdevice-86c69bca13a6c44e26e980ee4fbbfdff
    - nodeSelector:
        kubernetes.io/hostname: node4
      poolConfig:
        dataRaidGroupType: stripe
        compression: lz4
      dataRaidGroups:
        - blockDevices:
          - blockDeviceName: blockdevice-7fa570ac5d6eb4e393fb19982a82fa1b
