apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - https://github.com/jetstack/cert-manager/releases/download/v1.10.1/cert-manager.yaml

patches:
  - path: ./patches/certmanager_namespace.yaml
  - path: ./patches/cainjector_namespace.yaml
