apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml

patchesStrategicMerge:
  - ./patches/certmanager_namespace.yaml
  - ./patches/cainjector_namespace.yaml
