apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediaserver
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: k8s.qt.rs
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - sonarr-anime.k8s.qt.rs
        - sonarr-tv.k8s.qt.rs
        - radarr.k8s.qt.rs
        - jackett.k8s.qt.rs
        - tautulli.k8s.qt.rs
        - qbittorrent.k8s.qt.rs
      secretName: mediaserver-k8s-qt-rs
  rules:
    - host: sonarr-anime.k8s.qt.rs
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr-anime
                port:
                  name: http
    - host: sonarr-tv.k8s.qt.rs
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr-tv
                port:
                  name: http
    - host: radarr.k8s.qt.rs
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  name: http
    - host: jackett.k8s.qt.rs
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jackett
                port:
                  name: http
    - host: qbittorrent.k8s.qt.rs
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbittorrent
                port:
                  name: http
    - host: tautulli.k8s.qt.rs
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tautulli
                port:
                  name: http
    - host: mediaserver.k8s.qt.rs
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: organizr
                port:
                  name: http
