apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediaserver-anime
spec:
  accessModes:
    - ReadWriteMany
  claimRef:
    name: mediaserver-anime
    namespace: mediaserver
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/tank/anime
    server: truenas.node.tq.rs
    readOnly: false
  mountOptions:
    - vers=3
  capacity:
    storage: 15Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediaserver-movies
spec:
  accessModes:
    - ReadWriteMany
  claimRef:
    name: mediaserver-movies
    namespace: mediaserver
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/tank/movies
    server: truenas.node.tq.rs
    readOnly: false
  mountOptions:
    - vers=3
  capacity:
    storage: 3Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediaserver-tv
spec:
  accessModes:
    - ReadWriteMany
  claimRef:
    name: mediaserver-tv
    namespace: mediaserver
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/tank/tv
    server: truenas.node.tq.rs
    readOnly: false
  mountOptions:
    - vers=3
  capacity:
    storage: 2Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediaserver-music
spec:
  accessModes:
    - ReadWriteMany
  claimRef:
    name: mediaserver-music
    namespace: mediaserver
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/tank/music
    server: truenas.node.tq.rs
    readOnly: false
  mountOptions:
    - vers=3
  capacity:
    storage: 1Ti
