apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediaserver
spec:
  accessModes:
    - ReadWriteMany
  claimRef:
    name: mediaserver
    namespace: mediaserver
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/tank/media
    server: truenas.node.tq.rs
    readOnly: false
  mountOptions:
    - vers=3
  capacity:
    storage: 23Ti
