apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaserver
  labels:
    app.kubernetes.io/name: mediaserver
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 23Ti
