apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:jWaJkx1BMcFwXXAW+YggL7XXuwuGqiy1lhQA/pmeZZeT1VWvNCteWw==,iv:5FYofbIobnlEeF0tj9FRg+2aaCgO+kmjFzwHPKSf6fA=,tag:HE3ktQa+HaVXISiZC7Pb0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h0exhkky2vwydazymcpwccf8dvlm3u0sg0rj0zn7dz82s5zglguscnemkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTkJhR2MxOHl1bEcwTTl5
            eFoyVVJheFRGaGRLSjJZdmVNZkpqbHR3Nm1nCmU0ZEhGajFHMmZzS09yRDZxQTdi
            eUJaMk51WDZTY3pjZEJ4dUxqNTZQWnMKLS0tIHliWDRrckVyQ3BweGpHM2UwTWxR
            d1Y1aG02OXBCcGpNRVAzM0RrOFBIVWMKHdIbuNHahXlWum480ui3KpzA2Z64PrMF
            g0EyZYG7XRzFfkJNvoqKc6dTFiDzpCf8XWPPoeOW0VH08xFDJ/3a5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-04-06T02:06:36Z"
    mac: ENC[AES256_GCM,data:F4j36Y473xUaWdZEnkjILzuI1ANqQ6phhXqermGVDjQFnkCnxGS3XEVITn7cwH+jZZCmXR9vfBrJVUgETU6wxmh8+/9E0eUbpDjY/8fzUA0pZDEPC4ThlyhcaQ0ctzgJ1u0jkubDZ4I4A62UVX6ZVWauekLWu9APDTd7N5CT0Wk=,iv:2v1bxfPAgR7Gy+ctfoEUKvGNNtKODbcUT3Tzx3zEFNE=,tag:+L9jj6/T+PeWkYKzEo1P4Q==,type:str]
    pgp:
        - created_at: "2023-05-31T03:43:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA2hwEhv/EBDcAQ//dIZz7xc1d9rdfur1NaCCedFs8I7fOcGbFeiixFM5xAz1
            6Zei38/akg6Ryapy+nURaFaxoeRFDRxQRcVOVCX6GHoSktQSPczk3Y/ub4Ghwfff
            48yg9ounUXxpHIsNxXF05GDAsVtI5yOHI0JJ0LkY6Nhmqcau0fXJ+NFTQCW/RCgD
            sVjklDul9g1viqrH9/dIsTlqSw+aIsOq4VmAVOrG6EEqkW64Ha7GhHmGncSw2P/K
            rqvNwyOf5rzRgCpnb+qjkT+Ha8RH7PyzTG55Hqdc5bFl1yIS6CqUnJrQUiRltH+z
            JShZFZZY4BTH8R+ZcJ5FCjFUUGgGeJtX1ZsDbCR9RN2CtqM4PE9k3Rtr9I7rjvIQ
            lJWkdv2JNVMCBkkjUnsOZ6jZFkSfraSgb7s0gOd8YfB9oswDL5KcJmOE8eAGjcZE
            NnpepgjUPnHRVaG9SIVqL1TvJVEg10NZgD5A5IJOvU9OOk153Sj4X8RGULQ8qOCV
            /6XJtehCXEbry6gyArPcH6TCSQ94mfvH+igow3hOne3kcVrbF8d3EtKTfGLfiZiB
            ZzT9AV3uetzoJQiwSyjM7U0sTjhvE1zpX2TjbfKq5Ykafl+iiqbJmDCh/wd2Zw5b
            6CVPJHGXOTwEUc6i1un+xcVtUwRJiHp3ns4aOs/O0F9Z5O6M0VNSa0sV78wUtpXS
            UQGc76iBtBN/tSC4oSYZN/nfnCT3EG/S443F9frdXCHfnANTgs4Pder1UrgCLYR2
            W4oofHMzDhpLMOX6PoVbK+vd3du1mzKUPeKSn9Xv91OqBg==
            =Asqr
            -----END PGP MESSAGE-----
          fp: 328820E009708FDD29C08DBA1D0261F6BCA46C6E
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
