apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./resources/namespace.yaml

helmGlobals:
  chartHome: ./charts

helmCharts:
- name: argo-cd
  releaseName: argo-cd
  namespace: argocd
  version: v5.31.0
  repo: https://argoproj.github.io/argo-helm
  includeCRDs: true
  valuesFile: ./resources/helm-chart-values.yaml
  apiVersions:
  - monitoring.coreos.com/v1
  - policy/v1/PodDisruptionBudget
  - networking.k8s.io/v1
