apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:caepBnE=,iv:ftnrp8wrq4IAbO7datwdrvBSYPTDpHJvOfVSQq53mmY=,tag:AKuYiuNhfSb3wHGIDZVGYQ==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:W2bfWNdgmV5m+i+QjAvjJZWqMi28I1EztsEjYSvm8D8edp1qjGlxOV2dPlZ7rZun6EgNHtTugFA0FdwUOCoL/w==,iv:RfqMLAkqoxIZRC1gWN4ghJkPG0Ds9uGlsxRHKluxg5c=,tag:TT0wNE4w355SygfEVmD37w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-04T04:41:59Z'
    mac: ENC[AES256_GCM,data:Oho82gEcw2P2hyPNNIHD4awHaMZ7gvFdTw6lzwkneqS4N+LTNUDYzV+qkBhAcVlYiQ7ftPomrk7S+gCT6T594pVQN/2iRvews3f7hzFmRokEEqRuperODOJ9o1Eey7CBtSlvBZGkIWRk8DTdo7pgHlmRBLDLQUqZFLSRYXBoz6g=,iv:OgzNCL1z6Y3KN4x6IO1Gjs5TGZWZn82XKXYLnvETb0E=,tag:xPKrHXXxAP2JhwUFtgL+fg==,type:str]
    pgp:
    -   created_at: '2021-05-03T04:05:08Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA2hwEhv/EBDcARAACyxcW8oog2RT8O2VT+rK1YjmmD8y1t7CwJRDWM2YiROJ
            uv1W34xZhj0dBhThlqXMeBd7J56I+KPJt2+1VzXvAG76kK8PyZYor4wB97hvqLdM
            5+Kfg4oA0HUj664MeSI/j0Gdw0CaeBcTkTxAAd88r8YQHFZLAtgpROi1jZOQaElb
            ibWpI/N1uBPHFiuyfAtCLunn3VptiA2x1lNN7omSELjv//ybr2uA7RgJAAP56lM4
            0zZPJRnGyfU2rAU0tb8r//JsSPQeBDVq6PYfh6OOLp2p/nzB4FpQtA9krRqXEsxU
            E+nMB7fyfJ6GVz/Y+Nui6r87oSITgYe6Yt0Ib1QKpEgg8lyYscXcvD3Hsmxb4q0Z
            UP4XfxGSXAqMiH/QWb63Kmj7brArKh+lsNm3tq8hu4sd1NU5FsdIbZTv5PPEQqqe
            mxnEdHVWGwAZYBFDlPMPEYn//p4rvVT1lpTa22LlWr37bPZFsSrV8SdQ3Svfv5OU
            DZTCr57p3tehYsNo1rlJv9O2RVaymoHR6+YkgbJV+AlkJf8ecucrmlaWHQh29cSQ
            FPvGlxOZb0NUosPC1OWYIJUOw206E1l2kiuVqquZUz6vVTylnPIwhB661EjB2XWS
            nc0R5e13jRefM15Yw89Poq84YdjhqMCUmqT5HH+UemocvrODyX9PGMZD2RGtFVHS
            4AHko3kWS1AKtcxEDqnMLS8lxeG/6OAN4DLhxxXgFuKvUk0F4LHlbATFCC6kolxJ
            +D0kmnKjy3Q4KbDfofmrvq76Wnto1xngleSRi9tntcAEUGm8wM1tm+0T4qVjRJHh
            fUcA
            =N7pj
            -----END PGP MESSAGE-----
        fp: 328820E009708FDD29C08DBA1D0261F6BCA46C6E
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
