apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  labels:
    app.kubernetes.io/name: overseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: overseerr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: overseerr
    spec:
      containers:
        - name: overseerr
          image: ghcr.io/linuxserver/overseerr:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: mediaserver-permissions
          ports:
            - name: "http"
              containerPort: 5055
              protocol: TCP
          volumeMounts:
            - name: overseerr-config
              mountPath: /config
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /api/v1
              port: 5055
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1
              port: 5055
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
      volumes:
        - name: overseerr-config
          persistentVolumeClaim:
            claimName: overseerr-config
