apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
  labels:
    app.kubernetes.io/name: overseerr
spec:
  storageClassName: openebs-sc-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
