apiVersion: v1
kind: Service
metadata:
  name: overseerr
  labels:
    app.kubernetes.io/name: overseerr
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      targetPort: 5055
      port: 80
  selector:
    app.kubernetes.io/name: overseerr
