apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - ../../base

configMapGenerator:
  - name: config
    files:
      - ./configs/config

generators:
  - ./generators/secrets-generator.yml

patches:
  - ./patches/disable-metallb-speaker.yaml

generatorOptions:
  disableNameSuffixHash: true
