nameOverride: traefik
fullnameOverride: traefik
namespaceOverride: traefik

image:
  registry: docker.io
  repository: traefik
  tag: 2.9.10

globalArguments:
- --global.checknewversion

additionalArguments:
- "--accesslog=true"

serviceAccountAnnotations:
  kustomize.config.k8s.io/behavior: replace

autoscaling:
  enabled: false
deployment:
  kind: Deployment
  replicas: 2

# Disable internal cert resolvers because of Cert Manager
certResolvers: {}

hub:
  enabled: false

metrics:
  prometheus:
    service:
      enabled: true
    # Enable ServiceMonitor with the next settings
    serviceMonitor:
      jobLabel: traefik
      interval: 30s
      honorLabels: true

ingressClass:
  enabled: true
  isDefaultClass: false

ingressRoute:
  dashboard:
    # I have my own route setup
    enabled: false

providers:
  kubernetesIngress:
    ingressClass: traefik

podDisruptionBudget:
  enabled: true
  minAvailable: 1

ports:
  web:
    redirectTo:
      port: websecure
  # V3-only feature
  # websecure:
  #   asDefault: true

service:
  ipFamilyPolicy: PreferDualStack

nodeSelector:
  node-role.kubernetes.io/worker: ""

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/name: '{{ template "traefik.name" . }}'
          app.kubernetes.io/instance: '{{ .Release.Name }}-{{ .Release.Namespace }}'
      topologyKey: kubernetes.io/hostname

deployment:
  additionalContainers:
  - image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
    imagePullPolicy: IfNotPresent
    name: oauth2-proxy
    ports:
    - containerPort: 4180
      name: oauth2-proxy
      protocol: TCP
    - containerPort: 44180
      name: oauth2-metrics
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /ping
        port: oauth2-proxy
        scheme: HTTP
      initialDelaySeconds: 0
      timeoutSeconds: 1
    readinessProbe:
      httpGet:
        path: /ping
        port: oauth2-proxy
        scheme: HTTP
      initialDelaySeconds: 0
      timeoutSeconds: 1
      successThreshold: 1
      periodSeconds: 10
    args:
      - "--http-address=0.0.0.0:4180"
      - "--metrics-address=0.0.0.0:44180"
      - "--email-domain=*"
      - "--cookie-name=_oauth2"
      - "--provider=github"
      - "--provider-display-name=GitHub"
      - "--scope=user:email"
      - "--upstream=static://202"
      - "--reverse-proxy=true"
      - "--redirect-url=https://auth.k8s.qt.rs/oauth2/callback"
      - "--cookie-domain=k8s.qt.rs"
      - "--whitelist-domain=.k8s.qt.rs"
      - "--skip-provider-button"
      - "--cookie-secure=true"
      - "--cookie-refresh=1h"
      - "--cookie-expire=168h" # 1 week
      - "--cookie-samesite=lax"
      # See https://github.com/oauth2-proxy/oauth2-proxy/issues/1937
      # See https://github.com/oauth2-proxy/oauth2-proxy/issues/817
      - "--cookie-csrf-per-request=true"
      - "--cookie-csrf-expire=5m"
      - "--cookie-refresh=5m"
    envFrom:
    - secretRef:
        name: oauth2-proxy-secrets
