apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ../../base
- ./resources/scc-rbac.yaml
- ./resources/ingress.yaml
- ./resources/projects.yaml
- ./resources/applications.yaml

patches:
- path: ./patches/argocd-gpg-keys-cm-patch.yaml
- path: ./patches/network-policy-patches.yaml
  target:
    kind: NetworkPolicy
    group: networking.k8s.io
    version: v1
    name: argocd-applicationset-controller

generators:
- |
  apiVersion: viaduct.ai/v1
  kind: ksops-exec
  metadata:
    name: not-important
  files:
  - ./secrets/deploy-sops-age-key.yaml
  - ./secrets/argocd-secret-patch.yaml
  - ./secrets/argocd-github-repo-creds.yaml

replacements:
- source:
    kind: ServiceAccount
    name: argocd-redis-ha
    namespace: argocd
    fieldPath: metadata.name
  targets:
  - select:
      name: argocd-scc
      kind: RoleBinding
    fieldPaths:
    - subjects.0.name
- source:
    kind: ServiceAccount
    name: argocd-redis-ha-haproxy
    namespace: argocd
    fieldPath: metadata.name
  targets:
  - select:
      name: argocd-scc
      kind: RoleBinding
    fieldPaths:
    - subjects.1.name
