annotations:
  artifacthub.io/changes: |
    - "⬆️ Upgrade traefik Docker tag to v2.9.10"
    - "feat: add additional labels to tlsoption"
apiVersion: v2
appVersion: v2.9.10
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
keywords:
- traefik
- ingress
- networking
kubeVersion: '>=1.16.0-0'
maintainers:
- email: emile@vauge.com
  name: emilevauge
- email: daniel.tomcej@gmail.com
  name: dtomcej
- email: ldez@traefik.io
  name: ldez
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: charlie.haley@traefik.io
  name: charlie-haley
name: traefik
sources:
- https://github.com/traefik/traefik
- https://github.com/traefik/traefik-helm-chart
type: application
version: 22.1.0
