apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./resources/namespace.yaml
- ./resources/scc.yaml
- ./resources/scc-rbac.yaml

# Somehow, the value specified in the Helm Chart is ignored
replicas:
- name: traefik
  count: 3

helmGlobals:
  chartHome: ./charts

helmCharts:
- name: traefik
  releaseName: traefik
  namespace: traefik
  version: 32.1.1
  repo: https://helm.traefik.io/traefik
  includeCRDs: true
  valuesFile: ./resources/helm-chart-values.yaml
  apiVersions:
  - monitoring.coreos.com/v1
  - policy/v1/PodDisruptionBudget
