apiVersion: v1
kind: Secret
metadata:
    name: traefik-forward-auth-secrets
type: Opaque
stringData:
    PROVIDERS_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:4Em0JY9lMZGKjV9HF4/ZUaJ8WAtrvwtrd4u9S46v2sr1w6x3aqd+Siit14OC3OsEbJkS7IEC619OxrXynV3k8Skz17XDLnP0,iv:SzC96U8vf4MR78ZSBR7IVfWNwIGFr9Nbj6ZFnMREi7I=,tag:Q+dbeSjZSWmGORP2V9oFGA==,type:str]
    PROVIDERS_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:HhmpAuLEHhgQAslxpTchBOdLfiB4oOKS,iv:O2O434ykSJHZiljTk5+K4CyO4hBBctgxypcACyfEG9s=,tag:ODMwnKk7NxzyFTTHc3VoCQ==,type:str]
    SECRET: ENC[AES256_GCM,data:B0qiDqYqPVUWGDDN2UmGMpqAaS4TjuiB/5h2LUyGCY6Va71Y49gVX6dbdZqPlvx6bHHYdy2p1L4lpvdtewP3fA==,iv:V6UL1AURTdgtvFjK8u+D7uioCIDthw2X64az3ufDuZc=,tag:ys899QqEhEUSJp/7d8Az3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-06T05:59:37Z'
    mac: ENC[AES256_GCM,data:3mVNkURG17L2Z0czQnYPlWIPX4YktBaR7MCITrz4dmcxPxfwqfGgSx0XpIgv5Z5EfPliTrfE0cxWSVhUgit4AZdBV5B3X4kzYly/4HzoLShN2U930QPE/mad76COHVz8unz3cbLLdu+7eWwCbRcLU4SLLayfOHGVhUiPJmCrAWk=,iv:qQeNOoN4g3TiaKt8m9zELJYZRZF0rTVE/u+lYn4VZDI=,tag:GkdeEzsH1wbFiOLRaXnv8w==,type:str]
    pgp:
    -   created_at: '2021-04-06T04:53:36Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA2hwEhv/EBDcARAAQpOO4/mdJBOdLgLJu7U03b2EMWJdzW3VZ3psJb0PHYTS
            WO6yLJ9a5+0Wur8mVkWinCXjx6BJoyqRp8JW9BBwN+ox2ZVPNCRM/Li6wQh6Tdf2
            WlPGGwpgF9HvnXGfIV5ThWM8v29IywAkAuqyz1SbglbDO5ftj9DQ+DlQfZlxR1AN
            H4IB/puv/xXvFNL3C/4RYob7ExfvOKNtqbURtPA7zWBDFjnsG2IDwMEdKPdUF5hi
            4IBKCPTl51ckwdEhLV43n1eBx61/EwbcS/M+RzzvoVvgxS7eiYhn3pjc7NR5Ktjl
            WRL9L/TTcRlUBjpr/L+xB2RQT8g4CaGFelAP9kE+UArS3cFAwKRZhqSRG1hWYSRe
            7nbK8cz7re6mzq4Ne0TGisSyaDMcwjdQ/1u2hLZt1ewN2ES7CJTmSFtv2/XMAD/+
            HXTKZpN6KXXUDtoxqN9KagZQiupejLw/0z+KHVJzJH8QgE131nsrtezSwairRQHk
            jVKPu0NQrdmYFiKUgLXCPQYe3PQ8+9O2TU9iF/ZxCI3GNuoDaEhCQTtYnfcaAUow
            124+wtT9SsakzP7+ZL2F1glY/tKPaXx7Cgb9lHtZefZ3q+YaKl2gZHOK58YR2EIF
            27CRosPVU8KfmdXFt3CGc6Ox4Mj066X7gDFouaXlqL74hE78u80ieD1OUiW381XS
            4AHkhmjbrOD8zrS2l8JkwKJ01eFojeAi4BjhoTHg0uJLTFhl4A3lBX6vyzH5fRy4
            eCUk4YY/KfauGG4N0hE59wnjoAEG9vzgxuT7wlpcvRx7KAU5RX+udFME4pImE23h
            gIgA
            =xvL8
            -----END PGP MESSAGE-----
        fp: 328820E009708FDD29C08DBA1D0261F6BCA46C6E
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
