apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mediaserver-scc
  namespace: mediaserver
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - mediaserver-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mediaserver-scc
  namespace: mediaserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mediaserver-scc
subjects:
- kind: ServiceAccount
  name: mediaserver
  namespace: mediaserver
