apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: mediaserver-scc
  namespace: mediaserver
  annotations:
    kubernetes.io/description: mediaserver-scc allows to run as root for non-rootless containers

# important: this SCC is scoped by RBAC rules
users: null
groups: null

allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
- SETPCAP
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
