apiVersion: v1
kind: Service
metadata:
  name: plex-tq-rs
spec:
  type: ExternalName
  externalName: "apoc.node.tq.rs"
  ports:
    - name: http
      protocol: TCP
      targetPort: 80
      port: 80
    - name: https
      protocol: TCP
      targetPort: 443
      port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-tq-rs
spec:
  type: ExternalName
  externalName: "proxmox.node.tq.rs"
  ports:
    - name: https
      protocol: TCP
      targetPort: 8006
      port: 443
