apiVersion: v1
kind: Endpoints
metadata:
  name: traefik-external-tq-rs
subsets:
  - addresses:
      - ip: 192.168.42.6
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-external-tq-rs
spec:
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: 80
# spec:
#   type: ExternalName
#   externalName:
