apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-monitoring

resources:
  - ./resources/deployment.yaml
  - ./resources/service.yaml
  - ./resources/network-policy.yaml

generators:
- |
  apiVersion: viaduct.ai/v1
  kind: ksops-exec
  metadata:
    name: not-important
  files:
  - ./secrets/webhook.yaml
