all:
  hosts:
    node1:
      ansible_host: 192.168.42.50
      ip: 192.168.42.50
      access_ip: 192.168.42.50
    node2:
      ansible_host: 192.168.42.51
      ip: 192.168.42.51
      access_ip: 192.168.42.51
    node3:
      ansible_host: 192.168.42.52
      ip: 192.168.42.52
      access_ip: 192.168.42.52
    node4:
      ansible_host: 192.168.42.53
      ip: 192.168.42.53
      access_ip: 192.168.42.53
  children:
    kube_control_plane:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube_control_plane:
        kube-node:
    calico-rr:
      hosts: {}
