apiVersion: v1
kind: Service
metadata:
  name: organizr
  labels:
    app.kubernetes.io/name: organizr
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      targetPort: 80
      port: 80
  selector:
    app.kubernetes.io/name: organizr
