# In this file, all applications running in
# our production cluster are listed. Simply add
# a new 'Application' resource to this list to
# sync them with Git.
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/berbiche/infrastructure
      revision: cluster-v2
      directories:
      # - path: k8s/argocd/overlays/prod
      - path: k8s/traefik/overlays/prod
      - path: k8s/cert-manager/overlays/prod
      - path: k8s/external-dns/overlays/prod
      - path: k8s/mediaserver/overlays/prod
  template:
    metadata:
      name: '{{path[1]}}'
    spec:
      project: production
      source:
        repoURL: https://github.com/berbiche/infrastructure
        targetRevision: cluster-v2
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: production
  source:
    repoURL: https://github.com/berbiche/infrastructure
    targetRevision: cluster-v2
    path: k8s/argocd/overlays/prod
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argocd
spec:
  project: production
  source:
    repoURL: https://github.com/berbiche/infrastructure
    targetRevision: cluster-v2
    path: k8s/csi/overlays/prod
  destination:
    namespace: democratic-csi
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: production
  source:
    repoURL: https://github.com/berbiche/infrastructure
    targetRevision: cluster-v2
    path: k8s/metallb/overlays/prod
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  syncPolicy: {}
