# In this file, all applications running in
# our production cluster are listed. Simply add
# a new 'Application' resource to this list to
# sync them with Git.
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/berbiche/infrastructure
      revision: cluster-v2
      directories:
      - path: k8s/argocd/overlays/prod
      - path: k8s/traefik/overlays/prod
  template:
    metadata:
      name: '{{path[1]}}'
    spec:
      project: production
      source:
        repoURL: https://github.com/berbiche/infrastructure
        targetRevision: cluster-v2
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          selfHeal: true
---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: traefik
#   namespace: argocd
# spec:
#   project: production
#   destination:
#     namespace: traefik
#     server: https://kubernetes.default.svc
#   source:
#     repoURL: https://github.com/berbiche/infrastructure
#     targetRevision: cluster-v2
#   syncPolicy:
#     automated:
#       selfHeal: true
