apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-scc
  namespace: argocd
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot-v2
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-scc
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-scc
subjects:
- kind: ServiceAccount
  name: $(ARGOCD-REDIS-HA)
  namespace: argocd
- kind: ServiceAccount
  name: $(ARGOCD-REDIS-HA-HAPROXY)
  namespace: argocd
