apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaserver

resources:
  - ./resources/namespace.yaml
  - ./resources/service-account.yaml
  - ./resources/scc.yaml
  - ./resources/scc-rbac.yaml
  - ./resources/apps/prowlarr
  - ./resources/apps/qbittorrent
  - ./resources/apps/radarr
  - ./resources/apps/sonarr
  - ./resources/apps/tautulli
  - ./resources/apps/overseerr
  # - ./resources/apps/organizr
