apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  labels:
    app.kubernetes.io/name: radarr
spec:
  storageClassName: ovirt-csi-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
