apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  # labels:
  #   app.kubernetes.io/name: prowlarr
spec:
  replicas: 1
  # selector:
  #   matchLabels:
  #     app.kubernetes.io/name: prowlarr
  template:
    # metadata:
    #   labels:
    #     app.kubernetes.io/name: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr:latest
          imagePullPolicy: Always
          ports:
            - name: "http"
              containerPort: 9117
              protocol: TCP
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 9696
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 9696
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config
