apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  # labels:
  #   app.kubernetes.io/name: jackett
spec:
  storageClassName: ovirt-csi-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
