apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      targetPort: http
      port: 80
  selector:
    app.kubernetes.io/name: prowlarr
