apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    app.kubernetes.io/name: jackett
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      targetPort: 9117
      port: 80
  selector:
    app.kubernetes.io/name: jackett
