apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-external-dns-secrets
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:VjMVUUIxP1t6e6BRZg1E4t4Adzx97AiTgyuTQXQKpc+9OzKc7dEIXA==,iv:yF+ig3n5knmyXDpPDbxTFWJY7kAFPz0ESijlxQ70QUU=,tag:43neiBx9sNrEwJIgg0J0Wg==,type:str]
    CF_ZONE_ID: ENC[AES256_GCM,data:n1FewFxu/MM/Bye6qev/x+1Ek15FowZl32hG2p9PF4k=,iv:aUbgMTY2mD2dzFRwMOywq+CymBVQ2iYK8vFznbdI/lk=,tag:dBwDbN1U/TwVQtTltXEwAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h0exhkky2vwydazymcpwccf8dvlm3u0sg0rj0zn7dz82s5zglguscnemkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTUdVTmdRWFZwNVcyUU1q
            Tml4R2tINmhzNG5QbWd3K2JLSkJHK2lQNmc4Ck1VU3RKZlFIaTFVL0E3NjJQK1hH
            VWdYYVFUZmdDWUgxMVpmOWNzWS92WTAKLS0tIEdhQ2JhclNyZ3hoNzNsZzl0dmNV
            eFgyV09Wb0hqdkdkTnliMGxya0IzSzAKkTL15OwVEB9wsz1DF6AePFxPOknd3Fyt
            nG85n01CRH5LvqOufs4TUjt67jrwW7k9Bp1oy97whS5PAo69Z3dtFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-04-10T02:49:30Z"
    mac: ENC[AES256_GCM,data:nWOq93tj64HwAo1MM1uZ+q0RV6ko6GUADzKRRL7/S3B+vsBMRj1zePUmL5fk6wFbgwYzWAfY5Quc93HclYYvqtFPAffklTDV4Jrs/IgxbGdkainjiEC74/UpkSU04T6xdhT6m66rMY7t08/A3zVOP7NCABaHoVigFJRFlgw/RWs=,iv:DKMVgSj+53gqC8+EEG+2hCKO7DTZ6Oub0ET8mn3QSe8=,tag:tVCB66kTfCqP1AXy++otdA==,type:str]
    pgp:
        - created_at: "2023-05-31T03:59:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA2hwEhv/EBDcAQ//arZq0UWd3u2rSkwNQ75j+5Zrq9SApCAn90Kf9qqlf+QN
            5IISeFEOrL9KhTCeWqB570zPfuQ3Pl1bpn9qoIUA61IYjBW4bqiXza41gtV1askj
            sgaql1wGzx/yOL3yzBPFaLeB6LUxSyCGodlNA9OXAnYjrLBRh/0jSAdOKteVg7qv
            oEVSgfBjnGCbK0ZS4sXe4c5LA3AuBH3ifVerva3z5s1KgI8eBpPBdk4EhhwRQvF9
            DO6Rdbnysp2esL6A8HMW1qMX3e1HQp19lNKh/9wUSGX4DJnbCeVD4fyXKowb25g9
            CMybAIQG7Gf2fW9+/aVp4WwH6zU8trs1kK4kVNuSG22aO6GRV/PB7ZarTFgOM16R
            KB01gHK8jQG/OWPz7eu47h1QXHQi/EpxAWLeOqcuG0WGCx6jvIgXTsY46k/eDiqR
            yiFGW4xgSN6H58RyN5+YUJYj/VCoB9Y6xWf/FgUq7SCJfEsAE8X5+u4nsY7Pdolq
            Rig8/FSA08uvIQ2GYvyPBQpVy4C+1xVaBcXo52Wy/rlKFMQG+A4G0yJnfCbNj4Ld
            2guDAaMWAyTeM/7koEjfRmx+Qkh+gexq0107jByotVv+cifsUjSARCH5oua/WiSX
            EId7qlUOTXKq+nWFmVOwWYdVaIO3femUYmVxNpAVcwacgVGcLWnjcZ5Mtuar/DTS
            UQHVpHqqQoKIVXoiQ+6Sb5SAk8jGpeEqfJC6ZKGb9I7PA9MO/kOV5btzaZFOt8D0
            KLq0pZ7zHUjxJJO08pZhSalFuno7kZEmw9R2CDdG1Z6zKg==
            =JXAk
            -----END PGP MESSAGE-----
          fp: 328820E009708FDD29C08DBA1D0261F6BCA46C6E
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
