apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-anime
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  storageClassName: openebs-sc-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-movies
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  storageClassName: openebs-sc-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
