apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  ports:
    - name: http
      protocol: TCP
      targetPort: http
      port: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: qbt-tcp-v4
  annotations:
    metallb.universe.tf/allow-shared-ip: "mediaserver-qbt-v4"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: bt
      protocol: TCP
      targetPort: bt-tcp
      port: 31136
---
apiVersion: v1
kind: Service
metadata:
  name: qbt-udp-v4
  annotations:
    metallb.universe.tf/allow-shared-ip: "mediaserver-qbt-v4"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: bt
      protocol: UDP
      targetPort: bt-udp
      port: 31136
