apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik
spec:
  selector:
    app.kubernetes.io/name: traefik
  ports:
  - name: oauth2-proxy
    port: 80
    targetPort: oauth2-proxy
    protocol: TCP
  type: ClusterIP
