apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
spec:
  ports:
    - name: dashboard-http
      port: 80
      targetPort: 9000
  selector:
    app.kubernetes.io/name: traefik
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
spec:
  ports:
    - name: traefik-forward-auth
      port: 80
      targetPort: 4181
  selector:
    app.kubernetes.io/name: traefik
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-prometheus
spec:
  ports:
    - name: metrics
      port: 9100
      targetPort: traefik
  selector:
    app.kubernetes.io/name: traefik
  type: ClusterIP
