apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: notImportantHere
chartName: openebs-monitoring
chartRepoUrl: https://openebs.github.io/monitoring
chartVersion: '0.2.1'
releaseName: openebs-monitoring
releaseNamespace: openebs
extraArgs:
  - --include-crds
values: ./configs/monitoring-helm-chart-values.yaml
