---
# - name: Deploy Kubespray
#   tags: deploy
#   become: yes
#   become_user: root
#   remote_user: automation
#   include_playbook: kubespray/cluster.yml

- name: Roles for OpenEBS nodes
  tags: provision
  hosts: openebs-node
  become: yes
  become_user: root
  remote_user: automation
  tasks:
    - name: 'Create the Hugepage configuration (at least 512Mb, creating 1Gb)'
      copy:
        dest: /etc/sysctl.d/20-openebs-hugepages.conf
        mode: '0644'
        owner: root
        group: root
        content: |
          vm.nr_hugepages=1024
      notify:
        - Reload sysctl
  handlers:
    - name: Reload sysctl
      become: yes
      become_user: root
      command: /usr/sbin/sysctl --system

- name: Roles for all nodes
  hosts: k8s-cluster
  become: yes
  become_user: root
  remote_user: automation
  tasks:
    - name: 'Install missing packages'
      apt:
        pkg:
          - nfs-common
          - open-iscsi
        state: present
        update_cache: yes
