apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
    annotations:
        kustomize.config.k8s.io/behavior: merge
type: Opaque
stringData:
    dex.github.clientID: ENC[AES256_GCM,data:OOEB9l5g+gam+lyjgfTJv8J+1lk=,iv:VvHmthwJpOc33uqs1Rfbbta1EYtY/Uk7PZ7l0Mvr/xE=,tag:wTJWlW242O3WHFuBn+n0Eg==,type:str]
    dex.github.clientSecret: ENC[AES256_GCM,data:y4oSnlPPNxsRWVrM1bUs9/bPEEBNyVhPsua0uXRP+Tnuj7B5mWCBIQ==,iv:5BhKSP+/3dn8iF5qCGSzML4PtaeCj+HYwKiL1ViHokE=,tag:OqLO2GGzL47W+d8pKFHqww==,type:str]
    webhook.github.secret: ENC[AES256_GCM,data:JWDyPwpJc9rxKyGL/oT98qt3w8YjnOHnZw1WklyovCP31QIGVZngmmB/XC46V/Z49VZJYZNdbt/1V2iT8JA6Hg==,iv:b7r5+5spyM6edBh7B89dwT4a/A3pemGsQ9ysffEB71U=,tag:g+XgSpf3Cb/yq2b0/Go5OQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h0exhkky2vwydazymcpwccf8dvlm3u0sg0rj0zn7dz82s5zglguscnemkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdG44TWVWWW5XY1RkZTN1
            Rml6SHBOZVN0czZ5TVdTNHl5eVpQTTZZNHljCnVhWmdURzBBVER4cVZpMXFvWnlN
            eDhOV0xXOVF5bkRPTTdhOVRVSWh2Z1kKLS0tIDRCYkhUeEtwRzRsQk40cmtJY2Fi
            TWtLOXIzTENmcVYzTEpua2o4ZVNOOG8KKYLBqF7v+5db/ZTxNIQ8Q5dZ51CyRlQG
            od+KKqaSor9rR8Ks986jQl2y7vqswWZgH2UmyUMZA68EnKujcCfFCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-30T17:36:53Z"
    mac: ENC[AES256_GCM,data:7QK81VvNYE/ZcuYTpO8VIZPETkEf5WN7gc2t/ze2/4U3lVHmj0xiuICJZBG70YXRPzPOhTMYgCo1KcRHn93dVslTOgqcy86QrMoVX4trqCorfs8Y6UDZXL0VqWqcQaGgoNuYnEBuWnGIRqM62/kdP7QCSzdzOzcsm/ycbFfY8nk=,iv:Z5U/e7Ph85jpKg9eJEM6dOxvXGlWgzHSsyTFS1n1AD0=,tag:Xp8FoKqe1kx//yWbk95gyQ==,type:str]
    pgp:
        - created_at: "2023-05-30T04:24:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA2hwEhv/EBDcAQ/+N/8oRaBUf/90kSRnFz6UJmdOCslnvzercgB2hQ2LwJZy
            hGZSpG25gnFQG34MPObuJn+3ecRIE0uBNcdbyTlUAdvoCFwry+2YlyW4NZOr1xrg
            yCEu6/aqiuO/yv5cL8T2pWz5k6KZT/Ac2e1jTx/AJ7Dnjscb9ZYuYj5tdoY4g9lN
            aYZaImwpvmHYERMqP/cQu8+1gdB1hVxFZ9dUlnWaDXHsfffAThNDDVzaWnmDwPXs
            xw27B1mn1t9pkUNDzGZtFfWlIGiWMZfYFy9gu2g7QFOMiiRQjoeYwcWhFSxVkOf3
            m9E7t6+HUhvsWVw2N6DvPfDpIFIoJ0NKnzm4Jt5bcDOnKx5GQKZDcTQzDes1QHFJ
            KSZyt4GQZFyx3gjDRiergqXhSZSGqTyedLgKIUhioUEuV4pFRECZG5FN487EFi6O
            JhTZ3CwK8sB5hLsdwZtc5hbgcH5+ZJbG7ObDK3dDBHuoJ01SZ3KjpNKQZrITM7kV
            kLSgDD8gv2FkVxdZfDIYlOsjIFICFDi+8LW4pfzxRDYq+6HKdJbmFxmfesdX7URv
            cYAzD8aUKMO3GRBeiwXBAm5ah/h+MqI6dqgZK6HbiiJ202Y47QG+KCIkclsbbPFD
            22CcEDiz909TWRTatISJR4mmHF0oTk33uaaFRV4RY0vRuzNIdv6ygb5K8CfQ217S
            UQGQFp1yl6ouU4PPdn6IUg0uKZz55+qczbq5XSiT6Ps35KWMjVLaMMT22DseC5Aw
            fzd7lEAUxjceOv8yNyR55UbBpt2ut1/G+SHDFiKSKlZISQ==
            =3QV1
            -----END PGP MESSAGE-----
          fp: 328820E009708FDD29C08DBA1D0261F6BCA46C6E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
