apiVersion: v1
kind: Secret
metadata:
    name: github-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:Iya2,iv:kcakyzMMxXdUPFPE5QsVKTg/BivlsN4jNBk7K9+zZvw=,tag:RJasfJXq4CraYErY893QjA==,type:str]
    url: ENC[AES256_GCM,data:YpVOm6q/6mk3sgO9R1Y7oooYYBvYsgcFs/vGNe6skjCuy6j62h8p/YrQ,iv:YVivYChEuMrbYMSOMPoLKplG2ZXfT+pBcj+9/L9Cz8g=,tag:IhAwhq3uHjseMStvEzMr4w==,type:str]
    githubAppID: ENC[AES256_GCM,data:C0cRUN3j,iv:ZTPRhTuciOFRA0ZF0lZmsAXpETm/o0pB1E3zdzwp1cI=,tag:lFCKMJmmqcNUXCvwBkZ0ow==,type:str]
    githubAppInstallationID: ENC[AES256_GCM,data:VVbKiQV0ofo=,iv:4BaZimUKoX8CqwpqHOQzKAfp+e85YfIxDfOpUB8Ohzo=,tag:jhj9hrmno5ppCCQ1KRgRfA==,type:str]
    githubAppPrivateKey: ENC[AES256_GCM,data:pgcyALQWXwAVQF4ea5D+ZHdqzmNqZtwNFjVWRM7gU8ktUeUMo4lmYtKGobou+CLMRl5c/JpqeRPuKKiDvLH80kO8DRQMZOLaYH4TaXY8106T2rXWJF+Ay9IvkWCNhBsVrtywAgLtml29xVL7Lzmn6lBnhmBFZs56aSWyJhLFcV+U9DPvXszU+3NZB6i41z6TAoY4UDyQ0ldyZ8AOQ/LKxvOLvdLKwEddp8U1JtvxrpENJISlR/TMKtqNeUF7O+ctuUHEq/RoyLN8zf0n6OPPw+C/JsvQaddGsDkUzUbKiv8zTrdTTjFZxqKEzpNxhX4MNhUX/naxrDCiBn+uV6EC5pZbeZR9Ey/pVlb/llocfoRV19tGk25cYw6x+XMCfcn+VlKdEMogPBWdQ0rb0nG90C0z/7/DFaoLbH3pdqgLOkV9cMERQEMQJER19rJyh3X6FmAQ5Yzawr1nKy5e0GKfjNBh3oVTmiyq6nYvMj5PESZCRvpMsKSGn0OcS20D47a3h1an3HwhffVpizwiTdXKaTetTzxvoNKztg5j6f/TTCP9y7QVjA7REzgYGcZYJjWA2YZMBfMa1QdpD/WYECmjWBNgv0S8fHuhUoX6siPbKN10PJgfVhjC16xt5g34KdOjUIm65DhYlAONnzERNzN8PPcqgQvoeno0o95n6Uu3ObKEtyW/+SjDxkQuYw4yUE1LD5WVn7Q1bjaW0sjhopRWQ0zKx2Ca6y1xcFEPHKLffeMR/H6eTtu1igUG4x9W9tU8OpoVJs5gq1TPHkh464poJIfQII3+Hx8jfMaF2t7bY1JvzudbpwNLhVoXiR0M2bPt4Qkun4IKNZV4mILHlJLmFPOPAxu/OCJlcZ+V9gtDoyetrNhlwSQOKiFsH0fgg6iKOn+A0UtAFlX3ec7DfUYNOTDKmat0S4Uk7bWjp8zdtJ7kGStdNP+go/0xXARL28gQT8ZC9TdPXwJcLiBfE+R9vvID6aWyzQGuda7glUGTKghxSmcx+BL5Ll/WaapZz5MrL/HiFWVJDC8uiGBgJyT0zoPCm3wbXRYKeD8gBBHoMNIKh36DrT8Tr0fTyigINH53VGtBNMgTeDuvQZJrRD8uiuagxMVRX0AM2JCzdGDv0vj2qgp0ywriidunNvqbOYKqL7WJgxJIe8M827285m2Z46AvN948vvm+sXFo1FSdvAPZOJcoVMV0dgtHa/jtAoMT01onZpmY1zDAC9C2xB8ZmScd0qpj2KfyeaM7y0PM2D9Jx6z/K889cuCGtwBc0AmPY4+l7pEFfX/Iy8HzbpOM5SmOpVTfKE1k0nWmh9LBilgzLIWaRM03SuL32EVSN6+MBnmxXG12/r/kGHJ9z1rkcYPODPnq8zo803uuR38wqflYivTg+aJCihnzgnF5RD8btTvg8rGxQ3UrgrVWS58Am7UynC3xKmx78N520Y/RAiLPaKpI5bXI/70tddg2GkZ8seFj00rQf5dMuAUe9xawoTpRu6WXgvKVDmyrT8WXcbi0dVU1dBoesbBzAZsJn2jorX5vHL+J3hCxw1q43uJgqVWOHW6fOsklKEt9jlpX53xcsjQOiCFCXZTvCCHFZ4/ApB77QoOOlWZvKpyqzwVX72RcFid8X/5C7jrKwgDm3pnLp8jb6Ec5Kx23P1Rt6sv0E40gTUr/hiIofksUHvdMM+zVH8+9n+5BArXbO5cxgqVixhvdEmDfR6NiaAP9bOYjJHC6W5dQJ0uILpS2vUNLT6R90TGHbyr0MJStV09bLmfVAOF3l+bfKlFiUTp/3VP0b3/b8K1FKhgS4G5hyqbCdBX9GhMPj/F5TVycxj39qEBiLiVmWt1CWpx4tFHq2rOKwesbDyiKoNb7mK+ZArBxMcWznwXVy9BSjGJhKCH04wljIIaJHOjTEw68Srz6yZ7PXph8QQnhUUC9+StnBrndEjmryK44txshyIZEx+SQOG0VtSw+Rw9NDxekrR9PauTPfSZvEW6+Bf5x5u3Er9Q8RAhxtqKBuDSK60gl/w/TNCaHY+Mw+gheN7xU/MN3SFJyoRygjqonN/++HjtJcx8+fa1nKSSFWFKG510itw0KRJtV6rytuJT08CupcX3q/bhq8kO596o4ZFl5DgDBlsats6+YjA5ZVlmvnsD+STorQgH023HgO3Bs8JPOD0z+vr+lwUZzf9uX+DYAsaxWpQdSU499GT4KBDT5GnZUeRbPRQXT1Qk4B3KFhrnm55WwJr7ysmbDnJZH5g==,iv:f1g0JO1ekPIpPd7rX/E+kFaGVzHzLfiVNo0rnUnS8b0=,tag:zgm5cwvzISZqQzZj68UfAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h0exhkky2vwydazymcpwccf8dvlm3u0sg0rj0zn7dz82s5zglguscnemkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOXNuMXJGdWpuYW5FcVRC
            WW9sd2RzRWJockVuL3VwV0R2Rnduem9WUlVnCmJxWVU1ZFBxZDEzTUJEQTBNMUlX
            aEJLdDV0cXpvc1dwWHJuZWhGM2R0SkUKLS0tIFB0Q2o0aUp2elBYendJaEtjZ1p2
            RFlpTjZrWDdjbGVsOTE2S1ZMbDFLWjgKMACwVssb2FXAzX/KDDb1HEo5nA/KQIm5
            cmoMlKpk7N3us0ud6ZtOH+m+TD4zkyZu5fziLEXG0jo9Oe+8b73+qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-30T21:14:56Z"
    mac: ENC[AES256_GCM,data:i0SZcJAPtkhzG5aGPzDlaxysvbwiTsJaCiAW4F9IrvM26xIUBDm43vzCV78e5pUTIrADcANB7Uyan7SAjUdVRi0Vt8NeP5TDBNUidd+ft5YEe3vfCFAyBszK1VkYAR3Y/JGTXnvi7pqYje2DZ87q3znEKgGPTNAAiIo1HMe6lMw=,iv:4j9loi5MyyxQ1G8XNASdkyoyUWARcPoupSdz+Hl/wNM=,tag:3ZmnX6ySwEZE3GmN7O7AiQ==,type:str]
    pgp:
        - created_at: "2023-05-30T20:59:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA2hwEhv/EBDcARAApmp6R0j6v4ZgE/ye1Vrg7qTRYgxLNaLksC6P092wT/el
            nVmhSP380QkNPkw516BKtnxHQBGeza/roOPp5XYP4FYsrUkEADonj6f5Q7I87VTC
            SrFzgCM9KNGgGjX8uJAnkPNOBmLLAMW90xHY4/C1hUA1WPboRMVZHHnG3cLZ+RJZ
            yc0K1l4hPTzgtRepgz6xtazV57/aouDSxKY5WpzT9NHQfyc4Tp9oyDtnoGYUv3DL
            2Cfg10BLoy1pFXbb85yZBvkHmNgDY8c9c8yuTwJej5JWwmY6K8LO8G8ouOiPgbR4
            Tgy9L99a2W73o1lH0nN8+rzTqSqQcSs8ghV4RDbdLYOWpgIys9jFR8dvcNBD6vTU
            1zvCMapvEcbjQ5mty9Yx1K2l/XJoRdoI1WzrDAQhh7DogrwiaC4O3GEszkQnpon5
            DBaFUtkYNMIAMBAI9UN7wP3efXBaYFsxrUfH3DqWya+o1bRQ8lZaVZqDjF7g5Mn4
            h92Hjzxi+TjuEhveK4hoAcepjY85QJOe1JSMIKtaxb38Bol6IJ1/aloIRK6n7eid
            bgWVy/BIL86dDHIPCE/5AlXy3OOzmYH2cl/GQ/x5pcjfa+6LsiwmTi3MHhtonqJk
            dxzJiH3Gl55kSrho+YbQu84DHSxGGEqj0Aws+A+mQcOqMGjE51tfdp7MMr1S8n3S
            UQE+38eNi3TPLPG03oOkFIRwjvjoticgncDRNw1MRPXCLU/LI61BG823BpcGIc5M
            lbd5fnXtQxoyNG5TPfh/wV1f6STv2qh9/r7no0Ul1CNCsQ==
            =d6UV
            -----END PGP MESSAGE-----
          fp: 328820E009708FDD29C08DBA1D0261F6BCA46C6E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
