apiVersion: v1
kind: Secret
metadata:
    name: deploy-sops-age-key
type: Opaque
stringData:
    keys.txt: ENC[AES256_GCM,data:1iG3X+xjvjlGmXGUl3mruVA6y6ChgCkFerakx3hHw9SYdI2vRlQ0PPwluHTVN0L+Cor3NHTSRhqqNMddr3VWw8GBysAPBktXT6Q=,iv:KjrJvg51CzOGlkxFQVfuqNwzES50XQkR95Lm96qZNM4=,tag:79HjOGqCobgzQzq7gP1g6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h0exhkky2vwydazymcpwccf8dvlm3u0sg0rj0zn7dz82s5zglguscnemkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dXR2SUtMME1wdEN1eE1W
            Yng2VHJjbThqNjN6VzM2Q0Qrbnp6TU5JU2tFClNTZk5hNm90Q1JRdWZaZE1KSDl2
            NjVBSmV3Qm9ZVit3a1dEbTZ6KzlCdlEKLS0tIHMySFNNVDYyeGF2Zk0ydytaekRa
            ZnU0V1VxMmx0UmpWeElqNEp1VkdQV3cKcBO6g1vi41KF6PbbYgx6N1sooJ4JXrJf
            XWEOlqdTrNrr0cPilyUB4vRSx9oWQN/ZEvKjtQOvnXMAWN0AYQN8OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-30T03:21:42Z"
    mac: ENC[AES256_GCM,data:1qeCjAJkTeJJ1HGtHU4N+vU12B7tBxe50Q6OpuOAyIVyG4F6SM61ouwfaln5R6gN2mkeUV0GZzopQpdi8qo8lYLj9BJ3e/ED+aMJKFzBxFDSbV5H8HRaa5lPF+cUnbQpAyKMiitSds9JGFzy9r/TkwfewHRzqto6lu9MmIPu9OI=,iv:MTGW/QPjdRMQVIgsub5z8VFT65/O5XKvfS4FfXPcUlg=,tag:91oHA4ltuVa+uu/2DwNQUg==,type:str]
    pgp:
        - created_at: "2023-05-30T03:23:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA2hwEhv/EBDcAQ//XCWFGiicP0mnO0prDf6z40JR0XZlr6EZOEknwx0IZdmC
            FYk2CSG974a6NMHogGxYg9Yv19oIX2F0G6QPqvFWpp+Xh6SKDXU/IGh0EQmfvhEC
            95gCisrsTKWt/9LvHPw5kB+HByuw+wuNP4fnDZxC8CU6xpYdY2bbHA2N2ZUNdFU9
            qoFVQn5gBBAgyvqYsITGLydBdJV921brwlLUpkEruWXuI8diqWU0/N4WXIIBZXhb
            3rfDmSGW0GLt/aVlCzJ4H71S+rpPDXJo1gYk8gg5mj4HBbiG8Mr0VPp/E/V9oLqU
            qTowSOIeknq/0nPZooUnr636KwxiG/T18hXfx2bHWIWuBTjxmWfRC4jdipgmi/AD
            XGM0OzPAUbrz699qjTl7ZdTR/ul4/6kfXMTbHvZiwmEjpedPeyVHvsI6vsjy3Blg
            8Xbx30S6oSq4sUWUBLRS7tXLwZYwlcQwlsbg2/K9RaxFNjhVsUkd36VW5hh1dfNq
            ndm3hYp5Gx8dGLzP0y27Ad/Db64g7mxewFP1KuJOU7wWM3A2HdEzIwF1WH7ArRRk
            lCZK4QL8Aa93iCvDf9NhDfgj7qinfkQxO+PQEg6blP4MbTE6qEEmjOSbZamMd0Bt
            aD3y6mDqp04678iytfGBDMTmDesVoEo4+mibD86hjX+Jig4Vwnoxc1bbjkTL+i7S
            UQFEwSdPX31eIKDahnLrXO3fO4M5VFSfzPfm0JB46zjllFKhCYPpqrLtOC1LQBHB
            4kyka72WtI6h6pajjAFGG+hQwALHIbR7TMLVQiQnZS7mUg==
            =VmwY
            -----END PGP MESSAGE-----
          fp: 328820E009708FDD29C08DBA1D0261F6BCA46C6E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
