apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  labels:
    app.kubernetes.io/name: tautulli
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli
    spec:
      serviceAccountName: mediaserver
      containers:
        - name: tautulli
          image: ghcr.io/linuxserver/tautulli:latest
          imagePullPolicy: Always
          ports:
            - name: "http"
              containerPort: 8181
              protocol: TCP
          # This is not a rootless image!
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
          volumeMounts:
            - name: tautulli-config
              mountPath: /config
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
      volumes:
        - name: tautulli-config
          persistentVolumeClaim:
            claimName: tautulli-config
