---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  labels:
    app.kubernetes.io/name: tautulli
spec:
  ports:
    - name: http
      protocol: TCP
      targetPort: 8181
      port: 80
  selector:
    app.kubernetes.io/name: tautulli
  type: ClusterIP
