name: renovate-config-validator

on:
  pull_request:
    branches:
      - cluster-v2
    paths:
      - renovate.json5
  push:
    branches:
      - cluster-v2
    paths:
      - renovate.json5

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: lts/Hydrogen
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.3
        with:
          config_file_path: renovate.json5
