name: renovate-config-validator

on:
  pull_request:
    branches:
      - cluster-v2
    paths:
      - renovate.json5
  push:
    branches:
      - cluster-v2
    paths:
      - renovate.json5

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: lts/Hydrogen
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@b54483862375f51910a60c4f498e927d4f3df466 # v1.0.1
        with:
          config_file_path: renovate.json5
