name: renovate-config-validator

on:
  pull_request:
    branches:
      - cluster-v2
    paths:
      - renovate.json5
  push:
    branches:
      - cluster-v2
    paths:
      - renovate.json5

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: lts/Hydrogen
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@36a15b83e37bf3221dc9c02ff5ffdaefb51ca1cf # v1.1.0
        with:
          config_file_path: renovate.json5
