apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaserver

resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/nfs-volume.yaml
- ./resources/nfs-pvc.yaml

# patchesStrategicMerge:
# - ./patches/qbittorrent-affinity.yaml

images:
- name: linuxserver/jackett
  newTag: latest
- name: linuxserver/radarr
  newTag: develop
- name: linuxserver/sonarr
  newTag: develop
- name: linuxserver/qbittorrent
  newTag: version-14.3.4.99202104180633-7350-2c8f322afubuntu20.04.1
- name: linuxserver/tautulli
  newTag: latest
- name: organizr/organizr
  newTag: latest

configMapGenerator:
  - name: mediaserver-permissions
    literals:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
