apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaserver

resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/nfs-volume.yaml
- ./resources/nfs-pvc.yaml

images:
- name: ghcr.io/linuxserver/prowlarr
  newTag: nightly@sha256:11844bc8261a493c43ba1af6d44c895cd898a967a2670263e2b3d22b11aa6b73
- name: ghcr.io/linuxserver/radarr
  newTag: develop@sha256:be66b12ab18a57c0148930ea9f8697936281d39a64ab3a4f1c866a4c762e0548
- name: ghcr.io/linuxserver/sonarr
  newTag: develop@sha256:e714a4688f9a62be08bf3126f76389c7e367eb3bff2c406b5cc492401a6f72f2
- name: ghcr.io/linuxserver/qbittorrent
  newTag: 4.5.5
- name: ghcr.io/linuxserver/tautulli
  newTag: latest@sha256:d72389637c2b3c44063ec142259cba8faf4252467f321645865bff26870babdb
- name: ghcr.io/linuxserver/overseerr
  newTag: latest@sha256:884c81c4f8c173cc22098a4cf8f2db27f353a7d6c9979f64dbe67d91ff1fb1b3

configMapGenerator:
  - name: mediaserver-permissions
    literals:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
