apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaserver

resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/nfs-volume.yaml
- ./resources/nfs-pvc.yaml

images:
- name: ghcr.io/linuxserver/prowlarr
  newTag: nightly@sha256:20249a977c824f9157ed360b4fb56e8cfd734a460fb3fbafd376fefd5b3b0d50
- name: ghcr.io/linuxserver/radarr
  newTag: develop@sha256:3c18609ab5237542461a9aaad3cedab8a5f3a0787a9a7408ad5f175e7d7fdd49
- name: ghcr.io/linuxserver/sonarr
  newTag: develop@sha256:611e40a2414284016778ca38942c1666b69df0e04656e24f0d6c7068dee37fb1
- name: ghcr.io/linuxserver/qbittorrent
  newTag: 4.5.5
- name: ghcr.io/linuxserver/tautulli
  newTag: latest@sha256:b265e48914776e8675f361b9ba771d33485e360ab20f63a3b86c1d7999a91362
- name: ghcr.io/linuxserver/overseerr
  newTag: latest@sha256:0d704a11a0c7f56a6091031b11413a6e017242ba18f787bf2a03f3979a18c95d

configMapGenerator:
  - name: mediaserver-permissions
    literals:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
