apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaserver

resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/nfs-volume.yaml
- ./resources/nfs-pvc.yaml

images:
- name: ghcr.io/linuxserver/prowlarr
  newTag: nightly@sha256:fd2599c13f5881dcee5a70845e7ea6edb86a66091e072764e69a8eebc4108ee7
- name: ghcr.io/linuxserver/radarr
  newTag: develop@sha256:4ca4bca61c763e1e37715c922a46a4588e1ad45fa11cbdc3692fa32f3b16e0fa
- name: ghcr.io/linuxserver/sonarr
  newTag: develop@sha256:721e8ffde576bc7658ba084b10a9b26f32fe189ea0ca1e6394c4c26fbbadabb6
- name: ghcr.io/linuxserver/qbittorrent
  newTag: 4.5.5
- name: ghcr.io/linuxserver/tautulli
  newTag: latest@sha256:85e41bfde7b0c13b4c68a20002429a4a5c57b4901dd42309b974edba86bbfad6
- name: ghcr.io/linuxserver/overseerr
  newTag: latest@sha256:27bbf04d7c16fc63858067ba7ad047fa71aea3d49b09a4fe56e5e9f96df5eb0a

configMapGenerator:
  - name: mediaserver-permissions
    literals:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
