apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaserver

resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/nfs-volume.yaml
- ./resources/nfs-pvc.yaml

images:
- name: ghcr.io/linuxserver/prowlarr
  newTag: nightly@sha256:e6cd5fb0b28f91bc69a6fa0411b494c3889016e3f36ade66ca32b9574131b84b
- name: ghcr.io/linuxserver/radarr
  newTag: develop@sha256:be66b12ab18a57c0148930ea9f8697936281d39a64ab3a4f1c866a4c762e0548
- name: ghcr.io/linuxserver/sonarr
  newTag: develop@sha256:ff553dd941c05084812dd16b202267fe1d2965ab210e23f7f4fd2de4345577d5
- name: ghcr.io/linuxserver/qbittorrent
  newTag: 4.5.5
- name: ghcr.io/linuxserver/tautulli
  newTag: latest@sha256:a6fab476c636acbb1f4ca0dffc11ae848efc94caf3ed4e10dfe37f11c3a8adb4
- name: ghcr.io/linuxserver/overseerr
  newTag: latest@sha256:ec7d421f7fb2f68e13432be59e64f67315dbe5c15a781df23f0409b537d2804c

configMapGenerator:
  - name: mediaserver-permissions
    literals:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
