apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaserver

resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/nfs-volume.yaml
- ./resources/nfs-pvc.yaml

images:
- name: ghcr.io/linuxserver/prowlarr
  newTag: nightly@sha256:7c442192e7f446841cdcdea81415b39a7f0e8644a74ac0fbd9c4f193d4d9c3ce
- name: ghcr.io/linuxserver/radarr
  newTag: develop@sha256:c8350709ac155d668a599214a0b8b06c15a38532b80237d72743d0858fcaee8d
- name: ghcr.io/linuxserver/sonarr
  newTag: develop@sha256:2616d79fb04643abaded403fbad3bee88efa736d5c2d66eb8f45d76742c512a8
- name: ghcr.io/linuxserver/qbittorrent
  newTag: 4.5.5
- name: ghcr.io/linuxserver/tautulli
  newTag: latest@sha256:4c410812526523427665c245f89e5244acb5169c9efaed0df7c1519bb9dea65c
- name: ghcr.io/linuxserver/overseerr
  newTag: latest@sha256:ce5f9433d4990395df2c8d9beeb6b13a55f17259f6299fc51eb5a7c37209431f

configMapGenerator:
  - name: mediaserver-permissions
    literals:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
