apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaserver

resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/nfs-volume.yaml
- ./resources/nfs-pvc.yaml

images:
- name: ghcr.io/linuxserver/prowlarr
  newTag: nightly@sha256:7c9ede0a8b6918d408ee3baf72640a145e99ea466fbadb7560ae194a2d31b4c7
- name: ghcr.io/linuxserver/radarr
  newTag: develop@sha256:24f3ec8b53723434bab74bef5a85b0ade0052873c12ee522960d5c1c26ff7fed
- name: ghcr.io/linuxserver/sonarr
  newTag: develop@sha256:e26891cf546a75ccd754935a43e8abf207b9b6adfa54f582769fc52eca7de043
- name: ghcr.io/linuxserver/qbittorrent
  newTag: 4.5.5@sha256:6ce86cd2924985385641d5bcac0234e82df2da8baa6e1e02b4c0a95635445410
- name: ghcr.io/linuxserver/tautulli
  newTag: latest@sha256:b2a2a615485103eb1e2b10bd0e29088be36b827495a643e433249c5dc945f1e6
- name: ghcr.io/linuxserver/overseerr
  newTag: latest@sha256:54cd6f5510c781a385c4d471364402d9cc5ecefad2728f32dd150d9333f67a65

configMapGenerator:
  - name: mediaserver-permissions
    literals:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
