apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaserver

resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/nfs-volume.yaml
- ./resources/nfs-pvc.yaml

images:
- name: linuxserver/prowlarr
  newName: ghcr.io/linuxserver/prowlarr
  newTag: nightly@sha256:201ceaa5a8c9b29068b02072fe75520812e881fd06f764f070efb9b8759e99ea
- name: linuxserver/radarr
  newName: ghcr.io/linuxserver/radarr
  newTag: develop@sha256:154014d3b29bb2db2d6f9ed50ed0569ade1d70b154f5724786ca92361602ffbf
- name: linuxserver/sonarr
  newName: ghcr.io/linuxserver/sonarr
  newTag: develop@sha256:3b9959bb948dc7d9e034d50026a34640667673942ab3adbd20b3a9b54bf18c2b
- name: linuxserver/qbittorrent
  newName: ghcr.io/linuxserver/qbittorrent
  newTag: 4.5.3
- name: linuxserver/tautulli
  newName: ghcr.io/linuxserver/tautulli
  newTag: latest@sha256:70fa8b9405cba434777c8f513d450bfe91c77de0feaccfaa051f3a43864b0c54
- name: ghcr.io/linuxserver/overseerr
  newTag: latest@sha256:623fff8d307b3911bde3abc9e104b4337717d92944ce5754fd865472f0f0b561

configMapGenerator:
  - name: mediaserver-permissions
    literals:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
