apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaserver

resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/nfs-volume.yaml
- ./resources/nfs-pvc.yaml

images:
- name: ghcr.io/linuxserver/prowlarr
  newTag: nightly@sha256:3700e685e534124d7b2213941ff1c3355563dce3dcce6fcd178182f75f00c32a
- name: ghcr.io/linuxserver/radarr
  newTag: develop@sha256:94b09d96bc26eeda0a2db640d1694d984fbb010b322849934184484776161d27
- name: ghcr.io/linuxserver/sonarr
  newTag: develop@sha256:8e6e4b3be32a33a2bbb95bf9df2afc7b5009e996bb18253b5f78b9abe19ccd80
- name: ghcr.io/linuxserver/qbittorrent
  newTag: 4.5.5
- name: ghcr.io/linuxserver/tautulli
  newTag: latest@sha256:586e22a48e8a2cfea679b619f1d797cd8e5f019a6317a2b441a004706e679f6c
- name: ghcr.io/linuxserver/overseerr
  newTag: latest@sha256:b15fc36e412021af043d81a8dbdec661382737a83b1e6012261d6706357d12e1

configMapGenerator:
  - name: mediaserver-permissions
    literals:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
