apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaserver

resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/nfs-volume.yaml
- ./resources/nfs-pvc.yaml

images:
- name: ghcr.io/linuxserver/prowlarr
  newTag: nightly@sha256:5c411c1be422ba880f4be4659777eb43198099c41611090ef004b68b5263646a
- name: ghcr.io/linuxserver/radarr
  newTag: develop@sha256:a9980e393385c3732ee4ad9246453b615408e7b8f0819e4f20c8cbb2c087c145
- name: ghcr.io/linuxserver/sonarr
  newTag: develop@sha256:f3b6522235c47ac7d47c5b7fe15875a04a1836e95e0d2f971fbbb046a7080f0a
- name: ghcr.io/linuxserver/qbittorrent
  newTag: 4.5.4
- name: ghcr.io/linuxserver/tautulli
  newTag: latest@sha256:0868eaeeb1ed4f3d79bb6b16176ce3887fb54eb7da1616aeb48462ce6527c20e
- name: ghcr.io/linuxserver/overseerr
  newTag: latest@sha256:6e8ef600d731db531efe6b328a93f4fb1215c91ea065d54b4138d27588181f4b

configMapGenerator:
  - name: mediaserver-permissions
    literals:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
