apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaserver

resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/nfs-volume.yaml
- ./resources/nfs-pvc.yaml

images:
- name: ghcr.io/linuxserver/prowlarr
  newTag: nightly@sha256:16e485976abd4e095190b69ce04c8ed79c2b4f9f5b0cc7289eafc349bb1e484f
- name: ghcr.io/linuxserver/radarr
  newTag: develop@sha256:3cbb28185b4df7e726339fa3461c0ab1407cc030823ac308bc91b933d0d0062b
- name: ghcr.io/linuxserver/sonarr
  newTag: develop@sha256:a3c1a218cf62bd31ddb7eb3c58e980a01b9f9ed5baa3b9b3a9352bb6853cc0eb
- name: ghcr.io/linuxserver/qbittorrent
  newTag: 4.5.5@sha256:6ce86cd2924985385641d5bcac0234e82df2da8baa6e1e02b4c0a95635445410
- name: ghcr.io/linuxserver/tautulli
  newTag: latest@sha256:a969f1b172448c7a021a0ee51f8eab0b94a2ccfc0435264fe02e2f4dfa515dd4
- name: ghcr.io/linuxserver/overseerr
  newTag: latest@sha256:a6eb6e6471a1c5440712ae8c7efeb5febc57678cfd16594eda98858fc29c80bf

configMapGenerator:
  - name: mediaserver-permissions
    literals:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
