apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaserver

resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/nfs-volume.yaml
- ./resources/nfs-pvc.yaml

images:
- name: ghcr.io/linuxserver/prowlarr
  newTag: nightly@sha256:846b82f6e548455e6ac9fa74fa0ca3528193d698a635aa668d81e99abb735f43
- name: ghcr.io/linuxserver/radarr
  newTag: develop@sha256:12f698380626d393495deca8f0655d83139071e1777c1e9dfce58194f83a613d
- name: ghcr.io/linuxserver/sonarr
  newTag: develop@sha256:e19f9f909003d53bea67958cf8f814118b04df62a72157eb2b8b19d88930ce1b
- name: ghcr.io/linuxserver/qbittorrent
  newTag: 4.5.5
- name: ghcr.io/linuxserver/tautulli
  newTag: latest@sha256:45ec9309450a6dd9bbf5760730642f2319d1f1e20aeb0bce6c8d0deafd2709fc
- name: ghcr.io/linuxserver/overseerr
  newTag: latest@sha256:a36bcc36ae644f1b4a3470dd64d3fabf8ef6a255f37ff669c4030a7166f2c174

configMapGenerator:
  - name: mediaserver-permissions
    literals:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
