apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaserver

resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/nfs-volume.yaml
- ./resources/nfs-pvc.yaml

images:
- name: linuxserver/prowlarr
  newName: ghcr.io/linuxserver/prowlarr
  newTag: nightly
- name: linuxserver/radarr
  newName: ghcr.io/linuxserver/radarr
  newTag: develop
- name: linuxserver/sonarr
  newName: ghcr.io/linuxserver/sonarr
  newTag: develop
- name: linuxserver/qbittorrent
  newName: ghcr.io/linuxserver/qbittorrent
  newTag: 4.5.0
- name: linuxserver/tautulli
  newName: ghcr.io/linuxserver/tautulli
  newTag: latest
- name: ghcr.io/linuxserver/overseerr
  newTag: latest

configMapGenerator:
  - name: mediaserver-permissions
    literals:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
